In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

17
0.6834569033893041


In [4]:
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[23 47 70]
[[43 54  9 19]
 [71 42 88 77]
 [ 2  6 88  3]]
[[[47  4]
  [92  8]
  [ 2 76]
  [72 23]]

 [[49 59]
  [35 68]
  [97 80]
  [72 40]]

 [[79  0]
  [83 55]
  [21 21]
  [16 57]]]


In [5]:
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.6330881627247148
[0.56943047 0.81069393 0.2629884 ]
[[0.89028051 0.56215011 0.75214091]
 [0.77140201 0.41989124 0.47028593]]


In [8]:
a=random.randint(100,size=(3,2)).ravel()
a

array([15,  8, 90, 99,  2, 53])

In [9]:
#single element will be selected
random.choice(a)

99

In [11]:
#for generating an array
random.choice([1,2,3,4,5],size=(4,4))

array([[2, 5, 3, 3],
       [4, 1, 1, 5],
       [1, 1, 2, 4],
       [3, 5, 1, 3]])

#Pandas:
1. Data manipulation,analysisand cleaning
2. Tabular amnipulated


#Creating a DataFrame
1. using 2 dictionaries

In [16]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'f':9}
data={"first":dict1,"second":dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

first  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [19]:
#simple dictonary-->DataFrame
d1={"name":["abc","xyz","pqr"],"address":["hyd","niz","ap"]}
df1=pd.DataFrame(d1)
df1

name address
0  abc     hyd
1  xyz     niz
2  pqr      ap

In [21]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9])
s2=pd.Series([12.23,23.34,34.45,45.56,56.67,67.78,34.45,23.34,67.4,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 column3
0      1.0    12.23       a
1      2.0    23.34       b
2      3.0    34.45       c
3      4.0    45.56       d
4      5.0    56.67       e
5      6.0    67.78       f
6      7.0    34.45       g
7      8.0    23.34       h
8      9.0    67.40       i
9      NaN    23.00       j

#Selecting the data from the DataFrame:
1. loc
2. iloc

In [24]:
df3["column3"]

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
Name: column3, dtype: object

In [23]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    34.45       c
3    45.56       d
4    56.67       e
5    67.78       f
6    34.45       g
7    23.34       h
8    67.40       i
9    23.00       j

In [30]:
#single column
df3.loc[:,"column1"]

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    9.0
9    NaN
Name: column1, dtype: float64

In [29]:
df3.loc[:,["column1","column2"]]

column1  column2
0      1.0    12.23
1      2.0    23.34
2      3.0    34.45
3      4.0    45.56
4      5.0    56.67
5      6.0    67.78
6      7.0    34.45
7      8.0    23.34
8      9.0    67.40
9      NaN    23.00

In [28]:
#extracting multiple column values
df3.loc[0:5,["column1","column2"]]

column1  column2
0      1.0    12.23
1      2.0    23.34
2      3.0    34.45
3      4.0    45.56
4      5.0    56.67
5      6.0    67.78

In [32]:
df3.iloc[:,0]

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    9.0
9    NaN
Name: column1, dtype: float64

In [33]:
df3.iloc[0:4,0:1]

column1
0      1.0
1      2.0
2      3.0
3      4.0

#Retrieving the information of DataFrame

In [34]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  9 non-null      float64
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(2), object(1)
memory usage: 368.0+ bytes


In [36]:
df3.shape

(10, 3)

In [37]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [38]:
df3.index

RangeIndex(start=0, stop=10, step=1)

#Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [39]:
#first 5 rows
df3.head()

column1  column2 column3
0      1.0    12.23       a
1      2.0    23.34       b
2      3.0    34.45       c
3      4.0    45.56       d
4      5.0    56.67       e

In [40]:
df3.head(3)

column1  column2 column3
0      1.0    12.23       a
1      2.0    23.34       b
2      3.0    34.45       c

In [41]:
df3.sample()

column1  column2 column3
7      8.0    23.34       h

In [42]:
df3.sample(2)

column1  column2 column3
2      3.0    34.45       c
1      2.0    23.34       b

In [44]:
df3.describe()

column1   column2
count  9.000000  10.00000
mean   5.000000  38.82200
std    2.738613  19.70421
min    1.000000  12.23000
25%    3.000000  23.34000
50%    5.000000  34.45000
75%    7.000000  53.89250
max    9.000000  67.78000

In [46]:
#Remaining the column headers
df3.rename(columns={"column1":"First","column2":"second","column3":"Third"},inplace=True)
df3

First  second Third
0    1.0   12.23     a
1    2.0   23.34     b
2    3.0   34.45     c
3    4.0   45.56     d
4    5.0   56.67     e
5    6.0   67.78     f
6    7.0   34.45     g
7    8.0   23.34     h
8    9.0   67.40     i
9    NaN   23.00     j